```{r}
library(lubridate)
library(ggplot2)
useBytes = TRUE
my.data <- read.csv("avocado1.csv")
new.data <- my.data[my.data$region == "Albany", c("Date","Total.Volume","AveragePrice","X4046","X4225","X4770","region")]
new.data
new.data$Date <- as.Date(new.data$Date)
new.data <- new.data[new.data$Total.Volume >5000,]
ggplot(new.data, aes(Date,Total.Volume))+geom_point(color="blue",size=3, pch=18) + labs(title="牛油果總產量與時間關係圖(in Albany)")
```





```{r}
library(lubridate)
library(ggplot2)
library(readr)
useBytes = TRUE
my.data <- read.csv("avocado1.csv")
my.data
new.data <- my.data[my.data$region == "Albany", c("Date","Total.Volume","AveragePrice","X4046","X4225","X4770","region")]
new.data
new.data$Date <- as.Date(new.data$Date)
new.data <- new.data[new.data$Total.Volume >5000,]
ggplot(data=new.data)+
  geom_line(aes(x=Date,
                y=Total.Volume,
                color="total"
                ))+
  geom_line(aes(x=Date,
                y=X4046,
                color="4046"
                ))+
  geom_line(aes(x=Date,
                y=X4225,
                color="4225"
                ))+
  geom_line(aes(x=Date,
                y=X4225,
                color="4770"
                ))+
  labs(title="不同編號的牛油果產量與時間關係圖(in Albany)")
```






```{r}
library(ggplot2)
library(readr)
useBytes = TRUE
my.data <- read.csv("avocado1.csv")
my.data
new.data <- my.data[my.data$region == "Albany", c("Date","Total.Volume","AveragePrice","X4046","X4225","X4770","region")]
new.data <- rbind(new.data,my.data[my.data$region == "Boston", c("Date","Total.Volume","AveragePrice","X4046","X4225","X4770","region")])
new.data <- rbind(new.data,my.data[my.data$region == "Boise", c("Date","Total.Volume","AveragePrice","X4046","X4225","X4770","region")])
new.data <- new.data[new.data$Total.Volume >50000,]
new.data$Date <- as.Date(new.data$Date)
new.data
ggplot(data=new.data)+
  geom_line(aes(x=Date,
                y=Total.Volume,
                color=region
                )
            )+
  labs(title="比較三地區的牛油果總產量與時間關係")
```
